version: '3.6'
 
services:  
  app:
    build:
      context: ./app
    depends_on:
      - mysql
    environment:
        MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3001:5000"
  mysql:
    image: mysql
    volumes:
      - mysql_data:/data
volumes:  
  mysql_data: